spring.datasource.url=jdbc:postgresql://ep-cold-thunder-a1p8p7ai-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_5lkfVUOGt7Nj

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081

cashfree.appId=${CASHFREE_APP_ID}
cashfree.secretKey=${CASHFREE_SECRET_KEY}

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000