spring.datasource.url=jdbc:postgresql://ep-cold-thunder-a1p8p7ai-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_5lkfVUOGt7Nj

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081

cashfree.app_id=1245982d9b22316a529ef342b9f2895421
cashfree.secret_key=cfsk_ma_prod_c50d4cf72d48bbf94b885200c05fbbc9_aeb00f4c